---
- name: create ext volume for data
  file: state=directory path={{ ext_solr_logs_volume }}

- name: create ext volume for temp data
  file: state=directory path={{ ext_solr_temp_volume }}

#- name: create ext volume for configs
#  file: state=directory path={{ ext_hadoop_conf_volume }}

- name: check if a solr-nocloud-nohdfs container is started
  command: bash -c "docker ps | grep solr-nocloud-nohdfs"
  ignore_errors: True
  register: result

- name: start a solr-nocloud-nohdfs container
  command: docker run -d {% if docker_net_false|default(False) %} -n=false {% endif %} -h {{ ansible_hostname }}{% if docker_net_false|default(False) %}-sn{% endif %} --dns {{ ansible_docker0.ipv4.address }} --dns 8.8.8.8 --read-only=true --dns-search node.dc1.consul -v {{ ext_solr_temp_volume }}:/solr/server/solr-webapp -v {{ ext_solr_logs_volume }}:/solr/server/logs/ -p {{ solr_port }}:8983 -name solr-nocloud-nohdfs gitinsky/solr-nocloud-nohdfs:0.1.0
  register: docker_id
  when: result|failed

- name: start network
  shell: /root/ovswork.sh br10 {{ docker_id.stdout }} {{ network_map[ '' + ansible_hostname + '-sn' ] }}/24 {{ network_map[ '_broadcast' ] }} {{ network_map['_gateway'] }}
  when: (docker_id.changed == True) and (docker_net_false|default(False) == True)
